name: Publish Data Infrastructure
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "data/**"
      - ".github/workflows/data.yaml"

env:
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  DATABASE_URL: mysql://app:${{ secrets.MYSQL_PASSWORD }}@vargas-arts.c2sjnb5f4d57.us-east-1.rds.amazonaws.com:5432/app
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: get
        run: npx cdktf get
      - name: plan
        run: npx cdktf plan
      - name: apply
        run: npx fuego migrate
