name: Migrate DB
on:
  push:
    branches: main
    paths:
      - "app/migrations/**"
      - ".github/workflows/db.yaml"

env:
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  DATABASE_URL: mysql://app:${{ secrets.MYSQL_PASSWORD }}@vargas-arts.c2sjnb5f4d57.us-east-1.rds.amazonaws.com:5432/app
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.6
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: Install NPM 8
        run: npm install -g npm@latest
      - name: install
        run: npm install
      - name: migrate
        run: npx fuego migrate --overwrite 2022-04-16-11-add-code-column
