name: Migrate DB
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "app/migrations/**"
      - ".github/workflows/db.yaml"

env:
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  DATABASE_URL: mysql://app:${{ secrets.MYSQL_PASSWORD }}@vargas-arts.c2sjnb5f4d57.us-east-1.rds.amazonaws.com:5432/app
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.6
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: Install NPM 8
        run: npm install -g npm@latest
      - name: install
        run: npm install
      - name: migrate
        run: npx fuego migrate --overwrite 2022-03-22-19-43-fill-revenue-table --overwrite 2022-03-22-19-42-revenue-table --overwrite 2022-04-08-11-42-fix-revenue-table --overwrite 2022-04-09-04-47-fix-revenue-followup --overwrite 2022-04-11-12-23-remaining-stripe-payments --overwrite 2022-04-13-11-36-fix-charge-date --overwrite 2022-04-15-06-11-create-etherscan-table --overwrite 2022-04-16-10-16-create-expenses-table --overwrite 2022-04-16-11-41-add-code-column --overwrite 2022-04-16-11-54-personal-transfers-table
