name: Publish package
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "package.json"
      - ".github/workflows/package.yaml"
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.6
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: Use NPM 8
        run: npm install -g npm@latest
      - name: install
        run: npm install
      # - name: patch
      #   run: node patch.js
      - name: build
        run: npx tsc
      - name: prepare
        run: node prepare.js
      - name: write
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - name: publish
        run: npm publish --access public
        working-directory: dist
